### ISSUE TITLE
Is PDF/UA 7.5 test 1 too strict?

### ISSUE THREAD

**Issue by jzuidweg** [veraPDF/veraPDF-wcag-algs#104]
[This document](https://github.com/veraPDF/veraPDF-wcag-algs/files/7476542/Nota.De.Tweede.Helft.-.Ontwikkelingen.sportaccommodaties.2021-2030.pdf) fails **PDF/UA 7.5 test 1** ("_In a table not organized with Headers attributes and IDs, a TH cell does not contain a Scope attribute_") on all tables. However, these appear to be quite simple and valid tables that would not cause too many problems for reader software.

The implementation of the test itself appears to be correct, but my question is whether this is a serious enough error. Is this an example where PDF/UA is perhaps too strict with respect to WCAG 2.1?

I would not change or eliminate the test, as it forms part of the Matterhorn protocol, but I could choose to make it just a warning on the front end. What do you think?

**Comment by bdoubrov** [comment]
This error actually means that the assistive technologies will have problem detecting the relationship between header cells and ordinary cells. As far as I know this is quite important for screen readers.

If we look for example at the table on page 7, we see that all cells in the first table row are tagged as `<TH>`, while they are clearly not headers. So, this table is indeed badly tagged. The error we report might be indeed a bit confusing, but it actually means exactly this: missing relationship between headers and other cells. And normally this means some problems with table tagging.

**Comment by jzuidweg** [comment]
Thanks for the answer, I understand the point. It's true that the tester provided only a very simple example table, where assertive technologies don't have any problems understanding the table structure. But as you point out, in more complex tables it could be a problem if there is no clear relationship between header cells and data cells. So I won't disable this error in the front-end.

You can close this issue.
