### ISSUE TITLE
Figure element with no bounding box: false negative?

### ISSUE THREAD

**Issue by jzuidweg** [veraPDF/veraPDF-wcag-algs#111]
[This document](https://github.com/veraPDF/veraPDF-wcag-algs/files/7563511/eenvoudigdocmetafbeelding-zonder-bounding-box.pdf) does not raise an error in our PDF checker. 

However, in PAC3 it does give the error `"Figure" element on a single page with no bounding box.`

I've checked the Matterhorn Protocol but I can't find the failure criterium this PAC3 error refers to. I'm not sure whether this issue really affects people with reduced visibility using a PDF reader, but it _does_ affect the reflow function of Adobe Reader.

Could you check whether this is a test we should implement?

**Comment by bdoubrov** [comment]
I think the PAC issue originates from this PDF 1.7 wording (ISO 32000-1, Table 334 - Additional standard layout attributes specific to block-level structure elements):

> BBox - (Optional for Annot; required for any figure or table appearing in its entirety on a single page)

However, as it is not a part of Matterhorn protocol and doesn't seem to affect accessibility, we don't check for this.

**Comment by bdoubrov** [comment]
Discussed and resolved as follows:
- introduce this check for PDF/UA-1, but not for WCAG

Note that this requirement on BBox presence was weakened in PDF 2.0, where it was changed to a _should_ requirement (strongly recommended, but not a must).

**Comment by jzuidweg** [comment]
This is a difficult issue. If it's a PDF 1.7 requirement then it's also a PDF/UA requirement even if it is not part of the Matterhorn protocol. And if it affects reflow in readers, then you could argue it's also a WCAG issue.

I'm not sure how you resolved this issue in the end. I am still not getting any error when running the test file through the validator. Sorry to be a drag, but can we discuss this a little further?

**Comment by bdoubrov** [comment]
We are a bit reluctant adding this BBox check even in PDF/UA-1 case for the following reasons:
- This is not listed an an explicit requirement in the Matterhorn protocol
- This requirement was changed to a strong recommendation (but no longer mandatory) in PDF 2.0
- Acrobat's implementation of PDF/UA-1 syntax checks does not report missing BBox as an error

So, the only place where it exists at the moment is PDF 1.7 specification. Moreover, PDF 1.7 states that BBox is required also for Table elements located within a single page. But, for example, PAC3 does not complain about this. 

So, I'd say that is just a particular behavior of PAC3, which we don't necessarily need to duplicate.

**Comment by GehPlatVwaard** [comment]
The problem is on pages with images without a bounding box. These pages cannot be reflowed in Acrobat Reader (Ctrl+4).  Reflow can be used by partially sighted people. Tables without a bounding box can be reflowed. 

There are other options to reflow e.g. on basis of the tag structure as with VIP PDF reader. But this skips the image without a bounding box and shows only the alt-text which is also unexpected behaviour for partially sighted people.

**Comment by bdoubrov** [comment]
Thanks for the additional evidence. We'll add this check as a part of WCAG validation (but not for pure PDF/UA-1 validation)

**Comment by GehPlatVwaard** [comment]
Thanks, the test works fine
