### ISSUE TITLE
Unhandled exception during validation

### ISSUE THREAD

**Issue by bdoubrov** [veraPDF/veraPDF-wcag-algs#129]
The following document triggers unhandled exception during WCAG (Complete) validation:

[AERIUS_bijlage_20211201084741_Situatie1RZ8rg1NJyRJs.pdf](https://github.com/veraPDF/veraPDF-wcag-algs/files/7710777/AERIUS_bijlage_20211201084741_Situatie1RZ8rg1NJyRJs.pdf)

**Comment by MarinaSaroka** [comment]
Fixed and closed.
