### ISSUE TITLE
List over two pages

### ISSUE THREAD

**Issue by GehPlatVwaard** [veraPDF/veraPDF-wcag-algs#130]
This PDF document [List-over-two-pages.pdf](https://github.com/veraPDF/veraPDF-wcag-algs/files/7718306/List-over-two-pages.pdf) made with Word 365 contains one list splitted up over two pages. The PDF is made from Word with “Save as” and “PDF” selection in  the drop-down.
Unfortunately, Word makes an error in the PDF code. There are two lists L visible which should be one list.
Is it useful to signal an error in this case? E.g., based on the detection of two successive L-tags. Solution in Word is to limit a list to one page.

**Comment by jzuidweg** [comment]
This issue can be closed. However, I can't close it because I don't own it.

**Comment by GehPlatVwaard** [comment]
Thanks, I agree with the solution.
