### ISSUE TITLE
Table test

### ISSUE THREAD

**Issue by GehPlatVwaard** [veraPDF/veraPDF-wcag-algs#138]
The attached pdf made from Word with a table shows in the checker two remarks. Is this a table cell (4 cells)? and Is this a figure caption? All data table cells are TD labeled and I can't find any error in the file. 

The second attachment with the same table made by pdfmaker doesn’t show any remark in the pdfchecker.

[table-word.pdf](https://github.com/veraPDF/veraPDF-wcag-algs/files/7769639/table-word.pdf)
[table-pdfmaker.pdf](https://github.com/veraPDF/veraPDF-wcag-algs/files/7769640/table-pdfmaker.pdf)

**Comment by bdoubrov** [comment]
@GehPlatVwaard thanks for submitting this issue. It is cased by the slight difference in how table borders are drawn in these two documents. In one of the cases we incorrectly process the borders, which results in these unexpected error messages. This will be fixed in the next update

**Comment by GehPlatVwaard** [comment]
Boris, Thank you for your clear reaction. Regards Stephan Borgers, Gehandicapten Platform Valkenswaard

**Comment by MarinaSaroka** [comment]
Fixed and closed
