### ISSUE TITLE
PDF/UA 7.1 test 3 false positive?

### ISSUE THREAD

**Issue by jzuidweg** [veraPDF/veraPDF-wcag-algs#229]
[test-document-20.pdf](https://github.com/veraPDF/veraPDF-wcag-algs/files/9120194/test-document-20.pdf) fails PDF/UA 7.1 test 3 ('_Content is neither marked as Artifact nor tagged as real content_'). However, the author of this document says that Adobe Acrobat Pro does not report such error and she is not aware of any untagged content in the document.

Can you verify if there is indeed untagged content in the document, and whether the error for PDF/UA 7.1 test 3 was correctly raised?

See also [issue #222](https://github.com/veraPDF/veraPDF-wcag-algs/issues/222): it would be useful if the PDF checker could actually visualise the parts of the document that are not properly tagged.

**Comment by MaximPlusov** [comment]
For example, content stream 1662 0 contains 
```
0 0 595.275 420.945 re
f
```
and this rectangle don't tagged.

**Comment by jzuidweg** [comment]
Thanks Maxim. I think we can close this issue because this does not seem to be a false positive.
