### ISSUE TITLE
Implement equivalent of WCAG 4.1.2 test 20 for tables?

### ISSUE THREAD

**Issue by jzuidweg** [veraPDF/veraPDF-wcag-algs#87]
**WCAG 4.1.2 test 20** tries to detect captions below figures that have been tagged as ordinary paragraphs.

[This file](https://github.com/veraPDF/veraPDF-wcag-algs/files/7374516/tabel-met-tekst-eronder.pdf) contains a line directly below a table, and you would expect a warning that this appears to be a table caption tagged as a paragraph. However, this test has probably not been implemented yet.

Would it be possible to implement a test like WCAG 4.1.2 test 20 for lines directly below tables?

**Comment by bdoubrov** [comment]
We are going to support this along with the support for table borders.

**Comment by jzuidweg** [comment]
This issue has been tested and is solved. It can be closed.
