### ISSUE TITLE
Should we ignore PDF/UA 7.21.4.2 in the front-end?

### ISSUE THREAD

**Issue by jzuidweg** [veraPDF/veraPDF-wcag-algs#90]
[This small document](https://github.com/veraPDF/veraPDF-wcag-algs/files/7389236/lijst-arial.pdf) fails **PDF/UA 7.21.4.2 test 2** ('_True type (Open Type) font incorrectly identifies its glyphs_'). It flags this error for the font `Symbol MT` which is a TrueType (CID) font.

CID is an extension to TrueType which allows using only a partial set of symbols. Word appears to use this CID font for symbols which causes the error.

The validator correctly flags this error. It's not a false positive. However, an expert questioned whether this test is really relevant because reader applications such as NVDA don't have any problems with this. He argued that PDF/UA is sometimes (unnecessarily) stricter than WCAG.

I wouldn't change anything in the back-end because 7.21.4.2 is a valid PDF/UA test. However, we could consider ignoring this error in the front-end for non-tecnical users. Do you agree?

**Comment by bdoubrov** [comment]
Yes, I do agree this issue has very little relevance for accessibility and is a part of PDF/UA-1 syntax checks mainly for keeping font requirements in all PDF substandards synchronized. So, we can safely ignore it for the purposes of WCAG validation

**Comment by bdoubrov** [comment]
@jzuidweg would you please "ignore" errors 7.21.4.2-1 and 7.21.4.2-2 on the GUI side. They would stlull be a part of the validation profile though.

**Comment by jzuidweg** [comment]
This issue was a question and does not point to a bug or false positive/negative. The question has been answered. This issue can be closed.
